// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: healthcheck/v1/healthcheck.proto

package healthv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_healthcheck_v1_healthcheck_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_healthcheck_v1_healthcheck_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_healthcheck_v1_healthcheck_proto_rawDescGZIP(), []int{0}
}

type Dependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	mi := &file_healthcheck_v1_healthcheck_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_healthcheck_v1_healthcheck_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_healthcheck_v1_healthcheck_proto_rawDescGZIP(), []int{1}
}

func (x *Dependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dependency) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Dependency) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Dependencies  []*Dependency          `protobuf:"bytes,2,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_healthcheck_v1_healthcheck_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_healthcheck_v1_healthcheck_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_healthcheck_v1_healthcheck_proto_rawDescGZIP(), []int{2}
}

func (x *CheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CheckResponse) GetDependencies() []*Dependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

var File_healthcheck_v1_healthcheck_proto protoreflect.FileDescriptor

const file_healthcheck_v1_healthcheck_proto_rawDesc = "" +
	"\n" +
	" healthcheck/v1/healthcheck.proto\x12\x0ehealthcheck.v1\"\x0e\n" +
	"\fCheckRequest\"R\n" +
	"\n" +
	"Dependency\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"g\n" +
	"\rCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12>\n" +
	"\fdependencies\x18\x02 \x03(\v2\x1a.healthcheck.v1.DependencyR\fdependencies2Z\n" +
	"\x12HealthcheckService\x12D\n" +
	"\x05Check\x12\x1c.healthcheck.v1.CheckRequest\x1a\x1d.healthcheck.v1.CheckResponseB7Z5clean-template/internal/proto/healthcheck/v1;healthv1b\x06proto3"

var (
	file_healthcheck_v1_healthcheck_proto_rawDescOnce sync.Once
	file_healthcheck_v1_healthcheck_proto_rawDescData []byte
)

func file_healthcheck_v1_healthcheck_proto_rawDescGZIP() []byte {
	file_healthcheck_v1_healthcheck_proto_rawDescOnce.Do(func() {
		file_healthcheck_v1_healthcheck_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_healthcheck_v1_healthcheck_proto_rawDesc), len(file_healthcheck_v1_healthcheck_proto_rawDesc)))
	})
	return file_healthcheck_v1_healthcheck_proto_rawDescData
}

var file_healthcheck_v1_healthcheck_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_healthcheck_v1_healthcheck_proto_goTypes = []any{
	(*CheckRequest)(nil),  // 0: healthcheck.v1.CheckRequest
	(*Dependency)(nil),    // 1: healthcheck.v1.Dependency
	(*CheckResponse)(nil), // 2: healthcheck.v1.CheckResponse
}
var file_healthcheck_v1_healthcheck_proto_depIdxs = []int32{
	1, // 0: healthcheck.v1.CheckResponse.dependencies:type_name -> healthcheck.v1.Dependency
	0, // 1: healthcheck.v1.HealthcheckService.Check:input_type -> healthcheck.v1.CheckRequest
	2, // 2: healthcheck.v1.HealthcheckService.Check:output_type -> healthcheck.v1.CheckResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_healthcheck_v1_healthcheck_proto_init() }
func file_healthcheck_v1_healthcheck_proto_init() {
	if File_healthcheck_v1_healthcheck_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_healthcheck_v1_healthcheck_proto_rawDesc), len(file_healthcheck_v1_healthcheck_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_healthcheck_v1_healthcheck_proto_goTypes,
		DependencyIndexes: file_healthcheck_v1_healthcheck_proto_depIdxs,
		MessageInfos:      file_healthcheck_v1_healthcheck_proto_msgTypes,
	}.Build()
	File_healthcheck_v1_healthcheck_proto = out.File
	file_healthcheck_v1_healthcheck_proto_goTypes = nil
	file_healthcheck_v1_healthcheck_proto_depIdxs = nil
}
