// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sample/v1/sample.proto

package samplev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSampleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSampleRequest) Reset() {
	*x = CreateSampleRequest{}
	mi := &file_sample_v1_sample_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSampleRequest) ProtoMessage() {}

func (x *CreateSampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sample_v1_sample_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSampleRequest.ProtoReflect.Descriptor instead.
func (*CreateSampleRequest) Descriptor() ([]byte, []int) {
	return file_sample_v1_sample_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSampleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSampleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSampleRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetSampleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSampleRequest) Reset() {
	*x = GetSampleRequest{}
	mi := &file_sample_v1_sample_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSampleRequest) ProtoMessage() {}

func (x *GetSampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sample_v1_sample_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSampleRequest.ProtoReflect.Descriptor instead.
func (*GetSampleRequest) Descriptor() ([]byte, []int) {
	return file_sample_v1_sample_proto_rawDescGZIP(), []int{1}
}

func (x *GetSampleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListSamplesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSamplesRequest) Reset() {
	*x = ListSamplesRequest{}
	mi := &file_sample_v1_sample_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSamplesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSamplesRequest) ProtoMessage() {}

func (x *ListSamplesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sample_v1_sample_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSamplesRequest.ProtoReflect.Descriptor instead.
func (*ListSamplesRequest) Descriptor() ([]byte, []int) {
	return file_sample_v1_sample_proto_rawDescGZIP(), []int{2}
}

func (x *ListSamplesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSamplesRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type UpdateSampleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSampleRequest) Reset() {
	*x = UpdateSampleRequest{}
	mi := &file_sample_v1_sample_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSampleRequest) ProtoMessage() {}

func (x *UpdateSampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sample_v1_sample_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSampleRequest.ProtoReflect.Descriptor instead.
func (*UpdateSampleRequest) Descriptor() ([]byte, []int) {
	return file_sample_v1_sample_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSampleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSampleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSampleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateSampleRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteSampleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSampleRequest) Reset() {
	*x = DeleteSampleRequest{}
	mi := &file_sample_v1_sample_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSampleRequest) ProtoMessage() {}

func (x *DeleteSampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sample_v1_sample_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSampleRequest.ProtoReflect.Descriptor instead.
func (*DeleteSampleRequest) Descriptor() ([]byte, []int) {
	return file_sample_v1_sample_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSampleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSampleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSampleResponse) Reset() {
	*x = DeleteSampleResponse{}
	mi := &file_sample_v1_sample_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSampleResponse) ProtoMessage() {}

func (x *DeleteSampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sample_v1_sample_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSampleResponse.ProtoReflect.Descriptor instead.
func (*DeleteSampleResponse) Descriptor() ([]byte, []int) {
	return file_sample_v1_sample_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSampleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SampleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampleResponse) Reset() {
	*x = SampleResponse{}
	mi := &file_sample_v1_sample_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleResponse) ProtoMessage() {}

func (x *SampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sample_v1_sample_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleResponse.ProtoReflect.Descriptor instead.
func (*SampleResponse) Descriptor() ([]byte, []int) {
	return file_sample_v1_sample_proto_rawDescGZIP(), []int{6}
}

func (x *SampleResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SampleResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SampleResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SampleResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SampleResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SampleResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListSamplesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SampleResponse      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSamplesResponse) Reset() {
	*x = ListSamplesResponse{}
	mi := &file_sample_v1_sample_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSamplesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSamplesResponse) ProtoMessage() {}

func (x *ListSamplesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sample_v1_sample_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSamplesResponse.ProtoReflect.Descriptor instead.
func (*ListSamplesResponse) Descriptor() ([]byte, []int) {
	return file_sample_v1_sample_proto_rawDescGZIP(), []int{7}
}

func (x *ListSamplesResponse) GetItems() []*SampleResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListSamplesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_sample_v1_sample_proto protoreflect.FileDescriptor

const file_sample_v1_sample_proto_rawDesc = "" +
	"\n" +
	"\x16sample/v1/sample.proto\x12\tsample.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"c\n" +
	"\x13CreateSampleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\"\n" +
	"\x10GetSampleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x12ListSamplesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\"s\n" +
	"\x13UpdateSampleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"%\n" +
	"\x13DeleteSampleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14DeleteSampleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xe4\x01\n" +
	"\x0eSampleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\\\n" +
	"\x13ListSamplesResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.sample.v1.SampleResponseR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\x89\x03\n" +
	"\rSampleService\x12I\n" +
	"\fCreateSample\x12\x1e.sample.v1.CreateSampleRequest\x1a\x19.sample.v1.SampleResponse\x12C\n" +
	"\tGetSample\x12\x1b.sample.v1.GetSampleRequest\x1a\x19.sample.v1.SampleResponse\x12L\n" +
	"\vListSamples\x12\x1d.sample.v1.ListSamplesRequest\x1a\x1e.sample.v1.ListSamplesResponse\x12I\n" +
	"\fUpdateSample\x12\x1e.sample.v1.UpdateSampleRequest\x1a\x19.sample.v1.SampleResponse\x12O\n" +
	"\fDeleteSample\x12\x1e.sample.v1.DeleteSampleRequest\x1a\x1f.sample.v1.DeleteSampleResponseB2Z0clean-template/internal/proto/sample/v1;samplev1b\x06proto3"

var (
	file_sample_v1_sample_proto_rawDescOnce sync.Once
	file_sample_v1_sample_proto_rawDescData []byte
)

func file_sample_v1_sample_proto_rawDescGZIP() []byte {
	file_sample_v1_sample_proto_rawDescOnce.Do(func() {
		file_sample_v1_sample_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sample_v1_sample_proto_rawDesc), len(file_sample_v1_sample_proto_rawDesc)))
	})
	return file_sample_v1_sample_proto_rawDescData
}

var file_sample_v1_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sample_v1_sample_proto_goTypes = []any{
	(*CreateSampleRequest)(nil),   // 0: sample.v1.CreateSampleRequest
	(*GetSampleRequest)(nil),      // 1: sample.v1.GetSampleRequest
	(*ListSamplesRequest)(nil),    // 2: sample.v1.ListSamplesRequest
	(*UpdateSampleRequest)(nil),   // 3: sample.v1.UpdateSampleRequest
	(*DeleteSampleRequest)(nil),   // 4: sample.v1.DeleteSampleRequest
	(*DeleteSampleResponse)(nil),  // 5: sample.v1.DeleteSampleResponse
	(*SampleResponse)(nil),        // 6: sample.v1.SampleResponse
	(*ListSamplesResponse)(nil),   // 7: sample.v1.ListSamplesResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_sample_v1_sample_proto_depIdxs = []int32{
	8, // 0: sample.v1.SampleResponse.created_at:type_name -> google.protobuf.Timestamp
	8, // 1: sample.v1.SampleResponse.updated_at:type_name -> google.protobuf.Timestamp
	6, // 2: sample.v1.ListSamplesResponse.items:type_name -> sample.v1.SampleResponse
	0, // 3: sample.v1.SampleService.CreateSample:input_type -> sample.v1.CreateSampleRequest
	1, // 4: sample.v1.SampleService.GetSample:input_type -> sample.v1.GetSampleRequest
	2, // 5: sample.v1.SampleService.ListSamples:input_type -> sample.v1.ListSamplesRequest
	3, // 6: sample.v1.SampleService.UpdateSample:input_type -> sample.v1.UpdateSampleRequest
	4, // 7: sample.v1.SampleService.DeleteSample:input_type -> sample.v1.DeleteSampleRequest
	6, // 8: sample.v1.SampleService.CreateSample:output_type -> sample.v1.SampleResponse
	6, // 9: sample.v1.SampleService.GetSample:output_type -> sample.v1.SampleResponse
	7, // 10: sample.v1.SampleService.ListSamples:output_type -> sample.v1.ListSamplesResponse
	6, // 11: sample.v1.SampleService.UpdateSample:output_type -> sample.v1.SampleResponse
	5, // 12: sample.v1.SampleService.DeleteSample:output_type -> sample.v1.DeleteSampleResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sample_v1_sample_proto_init() }
func file_sample_v1_sample_proto_init() {
	if File_sample_v1_sample_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sample_v1_sample_proto_rawDesc), len(file_sample_v1_sample_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sample_v1_sample_proto_goTypes,
		DependencyIndexes: file_sample_v1_sample_proto_depIdxs,
		MessageInfos:      file_sample_v1_sample_proto_msgTypes,
	}.Build()
	File_sample_v1_sample_proto = out.File
	file_sample_v1_sample_proto_goTypes = nil
	file_sample_v1_sample_proto_depIdxs = nil
}
